name: Generate Weekly Post

on:
  schedule:
    - cron: "0 22 * * 3,6" # Toda quarta e sábado às 22:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate_post:
    runs-on: ubuntu-latest
    outputs:
      post_title: ${{ steps.generate_post.outputs.post_title }}
      post_slug: ${{ steps.generate_post.outputs.post_slug }}
      post_categories: ${{ steps.generate_post.outputs.post_categories }}
      post_tags: ${{ steps.generate_post.outputs.post_tags }}
      post_filename: ${{ steps.generate_post.outputs.post_filename }}
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instalar dependências
        run: pip install requests

      - name: Gerar post
        id: generate_post
        run: python generate_post.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Upload do post gerado como artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-post
          path: ${{ steps.generate_post.outputs.post_filename }}
          retention-days: 1

  create_pull_request:
    needs: generate_post
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Download do post gerado
        uses: actions/download-artifact@v4
        with:
          name: generated-post
          path: _posts/

      - name: Criar Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Add a new AI generated post"
          title: "New post: ${{ needs.generate_post.outputs.post_title }}"
          body: |
            ## This post was automatically generated by an AI.

            ### Post Information
            - Title: ${{ needs.generate_post.outputs.post_title }}
            - Slug: ${{ needs.generate_post.outputs.post_slug }}
            - Categories: `${{ needs.generate_post.outputs.post_categories }}`
            - Tags: `${{ needs.generate_post.outputs.post_tags }}`
            - File: [${{ needs.generate_post.outputs.post_filename }}](blob/posts/gerados-por-ia/${{ needs.generate_post.outputs.post_filename }})
          branch: "posts/generated-by-ai"
          author: "R. Daneel Olivaw <cleissonbarbosa68@gmail.com>"
          labels: "ai-generated,new-post"
          reviewers: "cleissonbarbosa"
          committer: "R. Daneel Olivaw <cleissonbarbosa@gmail.com>"
